# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('incident', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('times', models.IntegerField()),
            ],
        ),
    ]
